ys32-django/ajax/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.index),

    path('calcform', views.calcForm),
    path('calc', views.calc),

    path('loginform', views.loginForm),
    path('login', views.login),

    # path('uploadform', views.uploadForm),
    # path('upload', views.upload),

    path('uploadimageForm', views.uploadimageForm),
    path('uploadimage', views.uploadimage),

    path('runpythonform', views.runpythonForm),
    path('runpython', views.runpython),

    path('listuser', views.listUser),
] 

ys32-django/munich/urls.py
from django.urls import path, re_path
from munich import views

app_name = 'munich'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    ]

ys32-django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('ajax.urls')),
    path('loka/', include('loka.urls')),
    path('munich/', include('munich.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
   
]

ys32-django/munich/models.py
from django.db import models
from django.urls import reverse # url패턴을 만들어주는 장고의 내장 함수

# Create your models here.

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    # slug : 페이지나 포스트를 설명하는 핵심 단어의 집합. 콘텐츠의 고유 주소. 콘텐츠가 어떤 내용인지 쉽게 이해하도록 도움.
    # slugField :  제목의 단어들을 -으로 연결. url에서 pk대신 사용되는 경우가 많음. default length = 50
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'munich_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('munich:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

ys32-django/munich/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from munich.models import Post

# Create your views here.

#List View
class PostLV(ListView):
    model = Post
    template_name = 'munich/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

#Detail View
class PostDV(DetailView):
    model = Post

#Archive View
class PostAV(ArchiveIndexView):
    model = Post
    date_field ='modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field ='modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field ='modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    date_field ='modify_dt'

class PostTAV(TodayArchiveView):
    model = Post
    date_field ='modify_dt'

ys32-django/templates/munich/post_all.html
<h1>BAYERN MUNCHEN</h1>
<br>

{% for post in posts %}
<hr>
    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
    {{ post.modify_dt|date:"N d, Y"}}
    <p>{{ post.description }}</p>
    <hr>
{% endfor %}
<br>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
        {% endif %}
        Page {{ page_obj.unmber }} of {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next page</a>
        {% endif %}
    </span>
</div>

ys32-django/templates/munich/post_archive.html
<h1>Post Archive until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'munich:post_year_archive' date|date:'Y' %}">
                Year{{ date|date:"Y" }}
            </a>
        </li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_abs_url }}"><strong>{{ post.title }}
                </strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

ys32-django/templates/munich/post_archive_day.html
<h1>Post Archives for {{ dat|date:"N d, Y"}}</h1>

<div>
    <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
    </ul>
</div>

ys32-django/templates/munich/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y"}}</h1>

<div>
    <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify-dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

ys32-django/templates/munich/post_archive_year.html
<h1>Post Archive for {{ year|date:"Y"}}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'munich:post_month_archive' year|date:'Y' date|date:'b' %}">
                {{ date|date:"F" }}        
            </a>
        </li>
    {% endfor %}
</ul>
<br>
<div>
    <ul>
        {% for post in object_list %}
            <il>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </il>
        {% endfor %}
    </ul>
</div>

ys32-django/templates/munich/post_detail.html
<h2>{{ object.title }}</h2>
<p>
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
        &laquo;-{{ object.get_previous }}
    </a>
    {% endif %}

    {% if object.get_next %}
    |<a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        {{ object.get_next }} -&raquo;
    </a>
    {% endif %}
</p>
<p>
    {{object.modify_dt|date:"j F Y"}}
</p>
<br>
<div>
    {{ object.content|linebreaks }}
</div>