ys32-django/ajax/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.index),

    path('calcform', views.calcForm),
    path('calc', views.calc),

    path('loginform', views.loginForm),
    path('login', views.login),

    # path('uploadform', views.uploadForm),
    # path('upload', views.upload),

    path('uploadimageForm', views.uploadimageForm),
    path('uploadimage', views.uploadimage),

    path('runpythonform', views.runpythonForm),
    path('runpython', views.runpython),

    path('listuser', views.listUser),
] 

ys32-django/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkDV, BookmarkLV
 
app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
] 

ys32-django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('ajax.urls')),
    path('loka/', include('loka.urls')),
    path('munich/', include('munich.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
   
]

ys32-django/bookmark/models.py
from django.db import models

# Create your models here.


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

ys32-django/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

ys32-django/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>SECRET BOOKMARK DETAIL</title>
    </head>
    <body>
        <div id="content">
            <h1>{{ object.title }}</h1>
            <ul>
                <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
            </ul>
        </div>
    </body>
</html>

ys32-django/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>SECRET BOOKMARK</title>
    </head>
    <body>
        <div id="content">
            <h1>Bookmark List</h1>
            <ul>
                {% for bookmark in object_list %}
                <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>