ys32-django/ajax/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.index),

    path('calcform', views.calcForm),
    path('calc', views.calc),

    path('loginform', views.loginForm),
    path('login', views.login),

    # path('uploadform', views.uploadForm),
    # path('upload', views.upload),

    path('uploadimageForm', views.uploadimageForm),
    path('uploadimage', views.uploadimage),

    path('runpythonform', views.runpythonForm),
    path('runpython', views.runpython),

    path('listuser', views.listUser),
] 

ys32-django/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkDV, BookmarkLV
 
app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
] 

ys32-django/loka/urls.py
from django.urls import path
from . import views

app_name = 'loka'
 
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('<int:pk>/<mode>/', views.PostEditView.as_view(), name="edit"),
]


# get 요청
# 0/list : 리스트 출력
# 5/detail : 5번 post 출력
# 0/add : 신규 데이터 작성 -> post 발생
# 5/edit : 5번 post  수정 -> post 발생

ys32-django/munich/urls.py
from django.urls import path, re_path
from munich import views

app_name = 'munich'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    ]

ys32-django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('ajax.urls')),
    path('loka/', include('loka.urls')),
    path('munich/', include('munich.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
   
]

ys32-django/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}One. Two. Django!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% block extra-style %}{% endblock %}
    </head>
    <body style="padding-top: 90px;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">BEEK06</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'munich:index' %}">Munich</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'loka:login' %}">Loka</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Photo<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Util
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">admin</a>
                    <a class="dropdown-item" href="{% url 'munich:post_archive' %}">Archive</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Search</a>
                </div>
                </li>
                <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Global Search" aria-label="Search" name="search_word">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            </div>
        </nav>
        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
        {% block footer %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/c998a172fe.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/poppers.js/1.14.7/umd/popper.min.js"></script>
        
        {% block extra-script %}{% endblock %}

        
    </body>
</html>    

    

ys32-django/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}YSPARK WEB{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image{
    background-image: url("{% static 'img/moon.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title{
    color: #c80;
    font-weight: bold;
}
.powered{
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
    }
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">welcome!</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>ys.park</h4>
    </div>

<br><hr>
    
    <div class="rpw text-center">
        <div class="col-sm-6">
            <h3>Munich</h3>
            <p>This application makes it possible to log daily events or write useless things.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; Y.S.PARK</div>
</footer>
{% endblock %}

ys32-django/templates/template2.html
user List <button id="add">+</button><br>
{% for d in data %}

    이름 {{d.name}} age {{d.age}} <a href="listuser?userid={{d.userid}}">delete</a> <br>

{% endfor %}
<br>
<h1>검색기능</h1>
<form action="listuser">
    <input type="text" name="q">
    <input type="submit" value="search">
</form>

<br>
<h1>유저 추가</h1>
<div id="layer">
<form action="listuser" method="post">
    {% csrf_token %}
    <input type="text" name="userid">
    <input type="text" name="name">
    <input type="text" name="age">
    <input type="text" name="hobby">
    <input type="submit" name="+">    
</form>
</div>
<script>
    $("#layer").hide()
    $("#add").click(function(){
        $("#layer").toggle()
    });
</script>