ys32-django/ajax/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.index),

    path('calcform', views.calcForm),
    path('calc', views.calc),

    path('loginform', views.loginForm),
    path('login', views.login),

    # path('uploadform', views.uploadForm),
    # path('upload', views.upload),

    path('uploadimageForm', views.uploadimageForm),
    path('uploadimage', views.uploadimage),

    path('runpythonform', views.runpythonForm),
    path('runpython', views.runpython),

    path('listuser', views.listUser),
] 

ys32-django/loka/urls.py
from django.urls import path
from . import views

app_name = 'loka'
 
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('<int:pk>/<mode>/', views.PostEditView.as_view(), name="edit"),
]


# get 요청
# 0/list : 리스트 출력
# 5/detail : 5번 post 출력
# 0/add : 신규 데이터 작성 -> post 발생
# 5/edit : 5번 post  수정 -> post 발생

ys32-django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('ajax.urls')),
    path('loka/', include('loka.urls')),
    path('munich/', include('munich.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
   
]

ys32-django/loka/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()  # 글자수에 제한 없는 텍스트
    created_date = models.DateTimeField(
        default=timezone.now)  # 날짜와 시간
    published_date = models.DateTimeField(
        blank=True, null=True) #  필드가 폼에서 빈 채로 저장되는 것을 허용

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

ys32-django/loka/forms.py
from loka.models import Post
from django.forms import ValidationError
from django import forms


def validator(value) :
    if len(value) < 5 :
        raise  ValidationError("길이가 너무 짧아요")

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].validators = [validator]

ys32-django/loka/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from loka.models import Post
from django.views.generic import View
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import Form
from django.forms import CharField, Textarea, ValidationError
from . import forms

def index(request):
    return HttpResponse("Hello loka!")

class LoginView(View) :
    def get(self, request):
        return render(request, "loka/login.html")

    def post(self, request):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)
        
        if user == None :
            return redirect("/loka/login")        
        else:
            request.session["username"] = username
            return redirect("/loka/0/list")


class PostEditView(View):
    def get(self, request, pk, mode):
        if mode == 'list': # mode가 list일 때. pk 값은 상관이 없다.
            username = request.session.get('username', 'home')
            user = User.objects.get(username=username)
            data = Post.objects.all().filter(author=user) # author field로 검색 후 반환
            context = {'username':user, 'data':data} # html에서 읽기 위해 json화(=딕셔너리화) 시킴.
            return render(request, 'loka/list.html', context)
        elif mode == 'detail':
            post = get_object_or_404(Post, pk=pk) # DB내 Post table에서 요청된 pk 값과 일치하는 포스트 반환
            form = forms.PostForm(instance=post) # instance=post는 무엇을 위한 것인지 모르겠음. 아마 초기 값(원래 작성된 제목 및 본문)을 위한 것 같음.
            return render(request, 'loka/detail.html', {'form':form, 'pk':pk}) # detail.html에서 수정을 위해 pk 값을 넘겨주어야함. 따라서 pk 값을 전달인자에 포함시킴
        elif mode == 'add':
            form = forms.PostForm()
            return render(request, 'loka/edit.html', {'form':form})
        elif mode == 'edit': # 여기서 return이 없는데 이는 맨 밑에 return이 존재하기 때문이다. 즉 아래 edit으로 처음 접속하면(GET 방식으로) 아래 두 줄 수행 후 맨 밑의 return 코드가 실행된다.
            post = get_object_or_404(Post, pk=pk)
            form = forms.PostForm(instance=post)
        else: return HttpResponse('error') # mode에서 정의되지 않은 주소로 접속하면 보여줄 메세지.
        
        return render(request, 'loka/edit.html', {'form':form})
        
    def post(self, request, pk, mode):
        username = request.session["username"]
        user = User.objects.get(username=username)

        if pk == 0: # POST 방식으로 접근했을 때 pk가 0인 경우는 add 밖에 없다(?)
            form = forms.PostForm(request.POST)
        else:
            post = get_object_or_404(Post, pk=pk)
            form = forms.PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save(commit=False)
            if pk == 0:
                post.author = user
                post.save()
            else:
                post.publish()
            return redirect("edit",0,"list")
        return render(request, "loka/edit.html", {"form": form})

def validator(value) :
    if len(value) < 5 :
        raise  ValidationError("길이가 너무 짧아요")

class PostForm(Form):
    title = CharField(label='제목', max_length=20, validators=[validator])
    text = CharField(label="내용", widget=Textarea)

ys32-django/templates/loka/base.html
<font color=darkblue size=40>LOKA</font><br>

{{username}} 계정으로 로그인 되었습니다.<br><hr>

{% block content %}
{% endblock %}

<br><br><br><br><br><hr>
..copy right..<br>
..LOKABEEK06..

ys32-django/templates/loka/detail.html
{% extends 'loka/base.html' %}

{% block content %}

    <h2>Detail post</h2><br>

    {{form.as_p}}

    <a href="{% url 'edit' pk 'edit' %}">수정</a>

{% endblock%}

ys32-django/templates/loka/edit.html
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

 <style>
      .bg { background-color: #eeeeee; }
      .bd { border: 1px solid #666666; }
 </style>

{% if form.title.value %}
<h1>  수정하기 </h1>
{% else %}
<h1>  신규작성</h1>
{% endif %}


<form method=post>
   {% csrf_token %}
   	{{ form.as_p }}

   <input type="submit" value="작성" >

</form>

<script>
   $("#id_title").addClass('bg bd');
</script>

ys32-django/templates/loka/list.html
{% extends 'loka/base.html' %}

{% block content %}
<a href="{% url 'edit' 0 'add' %}">Add</a><br>
{%  for d in data %}
<a href="{% url 'edit' d.pk 'detail' %}"> {{d.title}} </a> <br>
{% endfor %}

{% endblock %}

ys32-django/templates/loka/login.html
<form action="{% url 'loka:login' %}" method=post>
    {% csrf_token %}
        username <input type=text name=username><br>
        password <input type=password name=password><br>
        <input type=submit value="login">
</form>